development:
  bitly:
    app_url: http://localhost:3001
  segment:
    app_url: http://localhost:3000
    front_url: http://localhost:3001
  facebook:
    redirect_url: https://localhost:3001/auth/facebook/callback
test:
  bitly:
    app_url: http://localhost:3001
  segment:
    app_url: http://localhost:3000
    front_url: http://localhost:3001
  facebook:
    redirect_url: https://localhost:3001/auth/facebook/callback
staging:
  bitly:
    app_url: 'https://staging.petparenthub.com'
  segment:
    app_url: https://staging-api.petparenthub.com
    front_url: https://staging.petparenthub.com
  facebook:
    redirect_url: https://staging.petparenthub.com/facebook/callback
