development:
  bitly:
    app_url: 'http://www.petparenthub.com'
  segment:
    app_url: http://localhost:3000/
    front_url: http://localhost:3001/
test:
  bitly:
    app_url: 'http://www.petparenthub.com'
  segment:
    app_url: http://localhost:3000/
    front_url: http://localhost:3001/
