FactoryBot.define do
  factory :rescue_groups_response, class: Hash do
    body do
      {'320':
        {'animalID': '320',
         'animalOrgID': '13',
         'animalActivityLevel': '',
         'animalAdoptionFee': '13.00',
         'animalAltered': '',
         'animalAvailableDate': '',
         'animalBirthdate': '',
         'animalBirthdateExact': 'No',
         'animalBreed': 'Domestic Short Hair',
         'animalCoatLength': '',
         'animalColor': '',
         'animalColorID': '',
         'animalColorDetails': 'Orange/White',
         'animalCourtesy': 'No',
         'animalDeclawed': 'No',
         'animalDescription': 'description',
         'animalDescriptionPlain': '',
         'animalDistinguishingMarks': '',
         'animalEarType': '',
         'animalEnergyLevel': '',
         'animalExerciseNeeds': '',
         'animalEyeColor': '',
         'animalFence': '',
         'animalFound': 'No',
         'animalFoundDate': '',
         'animalFoundPostalcode': '',
         'animalGeneralAge': 'Young',
         'animalGeneralSizePotential': '',
         'animalGroomingNeeds': '',
         'animalHousetrained': 'Yes',
         'animalIndoorOutdoor': '',
         'animalKillDate': '',
         'animalKillReason': '',
         'animalLocation': '20718',
         'animalLocationCitystate': 'Bowie, MD',
         'animalMicrochipped': '',
         'animalMixedBreed': 'No',
         'animalName': 'Corky',
         'animalSpecialneeds': '',
         'animalSpecialneedsDescription': '',
         'animalNeedsFoster': 'No',
         'animalNewPeople': '',
         'animalNotHousetrainedReason': '',
         'animalObedienceTraining': '',
         'animalOKWithAdults': '',
         'animalOKWithCats': 'Yes',
         'animalOKWithDogs': 'No',
         'animalOKWithKids': 'Yes',
         'animalOwnerExperience': 'None',
         'animalPattern': '',
         'animalPatternID': '0',
         'animalAdoptionPending': 'No',
         'animalPrimaryBreed': 'Domestic Short Hair',
         'animalPrimaryBreedID': '35',
         'animalRescueID': '',
         'animalSearchString': 'Corky  Orange/White  Male   Orange/White Cats Domestic Short Hairs',
         'animalSecondaryBreed': '',
         'animalSecondaryBreedID': '',
         'animalSex': 'Male',
         'animalShedding': '',
         'animalSizeCurrent': '',
         'animalSizePotential': '',
         'animalSizeUOM': 'Pounds',
         'animalSpecies': 'Cat',
         'animalSpeciesID': 'Cat',
         'animalSponsorable': 'No',
         'animalSponsors': '',
         'animalSponsorshipDetails': '',
         'animalSponsorshipMinimum': '',
         'animalStatus': 'Adopted',
         'animalStatusID': '3',
         'animalSummary': '',
         'animalTailType': '',
         'animalThumbnailUrl': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_100x61.jpg',
         'animalUptodate': '',
         'animalUpdatedDate': '7/12/2010 8:21 AM',
         'animalUrl': 'https://www.pgferals.org/animals/detail?AnimalID=13',
         'animalVocal': '',
         'animalYardRequired': '',
         'animalAffectionate': '',
         'animalApartment': '',
         'animalCratetrained': '',
         'animalDrools': '',
         'animalEagerToPlease': '',
         'animalEscapes': '',
         'animalEventempered': '',
         'animalFetches': '',
         'animalGentle': '',
         'animalGoodInCar': '',
         'animalGoofy': '',
         'animalHasAllergies': '',
         'animalHearingImpaired': '',
         'animalHypoallergenic': '',
         'animalIndependent': '',
         'animalIntelligent': '',
         'animalLap': '',
         'animalLeashtrained': '',
         'animalNeedsCompanionAnimal': '',
         'animalNoCold': '',
         'animalNoFemaleDogs': '',
         'animalNoHeat': '',
         'animalNoLargeDogs': '',
         'animalNoMaleDogs': '',
         'animalNoSmallDogs': '',
         'animalObedient': '',
         'animalOKForSeniors': '',
         'animalOKWithFarmAnimals': '',
         'animalOlderKidsOnly': '',
         'animalOngoingMedical': '',
         'animalPlayful': '',
         'animalPlaysToys': '',
         'animalPredatory': '',
         'animalProtective': '',
         'animalSightImpaired': '',
         'animalSkittish': '',
         'animalSpecialDiet': '',
         'animalSwims': '',
         'animalTimid': '',
         'fosterEmail': '',
         'fosterFirstname': '',
         'fosterLastname': '',
         'fosterName': '',
         'fosterPhoneCell': '',
         'fosterPhoneHome': '',
         'fosterSalutation': '',
         'locationAddress': '',
         'locationCity': '',
         'locationCountry': '',
         'locationUrl': '',
         'locationName': '',
         'locationPhone': '',
         'locationState': '',
         'locationPostalcode': '',
         'animalPictures':
          [{'mediaID': '181',
            'mediaOrder': '1',
            'lastUpdated': '8/9/2007 5:50 PM',
            'fileSize': '19096',
            'resolutionX': '350',
            'resolutionY': '216',
            'fileNameFullsize': '181_350x216.jpg',
            'fileNameThumbnail': '181_100x61.jpg',
            'urlSecureFullsize': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_350x216.jpg',
            'urlSecureThumbnail': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_100x61.jpg',
            'urlInsecureFullsize': 'http://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_350x216.jpg',
            'urlInsecureThumbnail': 'http://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_100x61.jpg',
            'original':
             {'type': 'Original',
              'fileSize': '19096',
              'resolutionX': '350',
              'resolutionY': '216',
              'url': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_350x216.jpg'},
            'large':
             {'type': 'Large',
              'fileSize': '19096',
              'resolutionX': '350',
              'resolutionY': '216',
              'url': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_350x216.jpg'},
            'small':
             {'type': 'Small',
              'fileSize': '2794',
              'resolutionX': '100',
              'resolutionY': '61',
              'url': 'https://s3.amazonaws.com/filestore.rescuegroups.org/13/pictures/animals/0/320/181_100x61.jpg'}}],
         'animalVideos': [],
         'animalVideoUrls': []
        }
      }
    end

    initialize_with { ActiveSupport::HashWithIndifferentAccess.new(attributes[:body]) }
  end

  factory :rescue_groups_organization_response, class: Hash do
    body do
      { 'orgAbout': 'description',
        'orgAdoptionProcess': '',
        'orgAdoptionUrl': '',
        'orgCommonapplicationAccept': 'No',
        'orgDonationUrl': '',
        'orgEmail': 'info@animalrelieffund.org',
        'orgFacebookUrl': '',
        'orgFax': '',
        'orgID': '16',
        'orgLocation': '20636',
        'orgAddress': 'P.O. Box 184',
        'orgCity': 'Hollywood',
        'orgCountry': 'United States',
        'orgLocationDistance': '',
        'orgPostalcode': '20636',
        'orgState': 'MD',
        'orgPlus4': '',
        'orgMeetPets': 'Most Saturdays from 11-2 at the Well Pet Clinic',
        'orgName': 'Animal Relief Fund',
        'orgPhone': '',
        'orgServeAreas': '',
        'orgServices': '',
        'orgSponsorshipUrl': '',
        'orgType': 'Rescue',
        'orgWebsiteUrl': 'webUrl'
      }
    end

    initialize_with { ActiveSupport::HashWithIndifferentAccess.new(attributes[:body]) }
  end
end